/**
*Text generated by Simple GUI Extension for BlueJ
*/
import javax.swing.UIManager.LookAndFeelInfo;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import javax.swing.border.Border;
import javax.swing.*;
import java.util.*;


public class GUI extends JFrame {

    private JMenuBar menuBar;
    private JButton button1;
    private JTextField textfield1;
    JPanel contentPane;
    private ArrayList<JButton> cards;
    private JButton temp;

    public GUI()
    {
        contentPane = new JPanel(null);
        cards = new ArrayList<JButton>();
        initGUI();
    }
    
    //Constructor 
    public void initGUI(){

        this.setTitle("Crazy Eights");
        this.setSize(800,600);
        //menu generate method
        generateMenu();
        this.setJMenuBar(menuBar);

        //pane with null layout
        contentPane.setPreferredSize(new Dimension(800,600));
        contentPane.setBackground(new Color(255,255,255));


        button1 = new JButton();
        button1.setBounds(270,560,90,35);
        button1.setBackground(new Color(214,217,223));
        button1.setForeground(new Color(0,0,0));
        button1.setEnabled(true);
        button1.setFont(new Font("sansserif",0,12));
        button1.setText("Enter");
        button1.setVisible(true);

        textfield1 = new JTextField();
        textfield1.setBounds(5,560,266,37);
        textfield1.setBackground(new Color(255,255,255));
        textfield1.setForeground(new Color(0,0,0));
        textfield1.setEnabled(true);
        textfield1.setFont(new Font("sansserif",0,12));
        textfield1.setText("Input");
        textfield1.setVisible(true);

        //adding components to contentPane panel
        contentPane.add(button1);
        contentPane.add(textfield1);

        //adding panel to JFrame and seting of window position and close operation
        this.add(contentPane);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.pack();
        this.setVisible(true);
    }

    //method for generate menu
    public void generateMenu(){
        menuBar = new JMenuBar();

        JMenu file = new JMenu("File");
        JMenu tools = new JMenu("Tools");
        JMenu help = new JMenu("Help");

        JMenuItem open = new JMenuItem("Open   ");
        JMenuItem save = new JMenuItem("Save   ");
        JMenuItem exit = new JMenuItem("Exit   ");
        JMenuItem preferences = new JMenuItem("Preferences   ");
        JMenuItem about = new JMenuItem("About   ");


        file.add(open);
        file.add(save);
        file.addSeparator();
        file.add(exit);
        tools.add(preferences);
        help.add(about);

        menuBar.add(file);
        menuBar.add(tools);
        menuBar.add(help);
    }
    
    public void addCard(int x, int y, int width, int height, int cardnum)//Adds a card to the screen
    {
        temp = new JButton();
        temp.setBounds(x, y, width, height);
        temp.setBackground(new Color(214,217,223));
        temp.setForeground(new Color(0,0,0));
        temp.setEnabled(true);
        temp.setFont(new Font("sansserif",0,12));
        temp.setText("Card " + cardnum);
        temp.setVisible(true);
        cards.add(temp);
        contentPane.add(cards.get(cardnum-1));
        this.add(contentPane);
    }
    
    public void removeCard()//Removes a card from the screen
    {
        
    }
}